// POST /api/admin/seed — inserts realistic demo data for the current user
// Safe to call multiple times (adds more data each time)

import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { scan, simulatedTrade, portfolio } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { getUser } from "@/lib/auth-utils";

function daysAgo(n: number, extraMs = 0): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return new Date(d.getTime() + extraMs);
}

export async function POST() {
  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // ─── 1. Scans ─────────────────────────────────────────────────────────
    const scanRows = await db
      .insert(scan)
      .values([
        {
          userId: user.id,
          status: "completed",
          symbols: ["BTCUSDT", "ETHUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [
            {
              id: "opp-1a",
              symbol: "BTCUSDT",
              buyExchange: "binance",
              sellExchange: "kraken",
              buyPrice: 94800,
              sellPrice: 95150,
              grossSpreadPct: 0.369,
              netSpreadPct: 0.269,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 3.12,
              confidence: 78,
            },
            {
              id: "opp-1b",
              symbol: "ETHUSDT",
              buyExchange: "kucoin",
              sellExchange: "binance",
              buyPrice: 3180,
              sellPrice: 3220,
              grossSpreadPct: 0.314,
              netSpreadPct: 0.214,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 19.55,
              confidence: 72,
            },
          ],
          triggeredAt: daysAgo(25),
          completedAt: daysAgo(25, 3200),
        },
        {
          userId: user.id,
          status: "completed",
          symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [
            {
              id: "opp-2a",
              symbol: "SOLUSDT",
              buyExchange: "bybit",
              sellExchange: "kraken",
              buyPrice: 178,
              sellPrice: 181.5,
              grossSpreadPct: 0.494,
              netSpreadPct: 0.394,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 17.1,
              confidence: 81,
            },
            {
              id: "opp-2b",
              symbol: "ETHUSDT",
              buyExchange: "gateio",
              sellExchange: "kraken",
              buyPrice: 3195,
              sellPrice: 3235,
              grossSpreadPct: 0.312,
              netSpreadPct: 0.212,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 31.45,
              confidence: 75,
            },
            {
              id: "opp-2c",
              symbol: "BTCUSDT",
              buyExchange: "bybit",
              sellExchange: "binance",
              buyPrice: 95200,
              sellPrice: 95600,
              grossSpreadPct: 0.42,
              netSpreadPct: 0.32,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 2.99,
              confidence: 69,
            },
          ],
          triggeredAt: daysAgo(20),
          completedAt: daysAgo(20, 2800),
        },
        {
          userId: user.id,
          status: "completed",
          symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "BNBUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [
            {
              id: "opp-3a",
              symbol: "XRPUSDT",
              buyExchange: "gateio",
              sellExchange: "binance",
              buyPrice: 0.545,
              sellPrice: 0.558,
              grossSpreadPct: 0.385,
              netSpreadPct: 0.285,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 6.35,
              confidence: 73,
            },
          ],
          triggeredAt: daysAgo(18),
          completedAt: daysAgo(18, 3100),
        },
        {
          userId: user.id,
          status: "completed",
          symbols: ["BTCUSDT", "XRPUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [],
          triggeredAt: daysAgo(15),
          completedAt: daysAgo(15, 2500),
        },
        {
          userId: user.id,
          status: "completed",
          symbols: ["ETHUSDT", "SOLUSDT", "BNBUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [
            {
              id: "opp-5a",
              symbol: "BNBUSDT",
              buyExchange: "kraken",
              sellExchange: "kucoin",
              buyPrice: 645,
              sellPrice: 652,
              grossSpreadPct: 0.431,
              netSpreadPct: 0.331,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 13.62,
              confidence: 77,
            },
            {
              id: "opp-5b",
              symbol: "SOLUSDT",
              buyExchange: "binance",
              sellExchange: "bybit",
              buyPrice: 180,
              sellPrice: 183,
              grossSpreadPct: 0.332,
              netSpreadPct: 0.232,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 23.55,
              confidence: 80,
            },
          ],
          triggeredAt: daysAgo(12),
          completedAt: daysAgo(12, 2900),
        },
        {
          userId: user.id,
          status: "completed",
          symbols: ["BNBUSDT", "XRPUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [],
          triggeredAt: daysAgo(8),
          completedAt: daysAgo(8, 2200),
        },
        {
          userId: user.id,
          status: "completed",
          symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "BNBUSDT"],
          exchanges: ["binance", "kraken", "kucoin", "bybit", "gateio"],
          rawPrices: null,
          opportunities: [
            {
              id: "opp-7a",
              symbol: "BNBUSDT",
              buyExchange: "kucoin",
              sellExchange: "gateio",
              buyPrice: 648,
              sellPrice: 655,
              grossSpreadPct: 0.432,
              netSpreadPct: 0.332,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 10.21,
              confidence: 76,
            },
            {
              id: "opp-7b",
              symbol: "XRPUSDT",
              buyExchange: "kraken",
              sellExchange: "bybit",
              buyPrice: 0.55,
              sellPrice: 0.562,
              grossSpreadPct: 0.435,
              netSpreadPct: 0.335,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 3.5,
              confidence: 71,
            },
            {
              id: "opp-7c",
              symbol: "ETHUSDT",
              buyExchange: "kucoin",
              sellExchange: "kraken",
              buyPrice: 3200,
              sellPrice: 3240,
              grossSpreadPct: 0.312,
              netSpreadPct: 0.212,
              estimatedFeePct: 0.1,
              estimatedProfitUsd: 28.5,
              confidence: 74,
            },
          ],
          triggeredAt: daysAgo(3),
          completedAt: daysAgo(3, 3400),
        },
      ])
      .returning({ id: scan.id });

    const ids = scanRows.map((r) => r.id);

    // ─── 2. Trades ────────────────────────────────────────────────────────
    const trades = [
      // Arbitrage — from scans
      {
        userId: user.id,
        scanId: ids[0],
        symbol: "BTCUSDT",
        buyExchange: "binance",
        sellExchange: "kraken",
        buyPrice: 94800,
        sellPrice: 95150,
        quantity: 0.01,
        grossProfit: 3.5,
        fees: 0.38,
        netProfit: 3.12,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 3.12,
        executedAt: daysAgo(25, 5_000),
      },
      {
        userId: user.id,
        scanId: ids[0],
        symbol: "ETHUSDT",
        buyExchange: "kucoin",
        sellExchange: "binance",
        buyPrice: 3180,
        sellPrice: 3220,
        quantity: 0.5,
        grossProfit: 20,
        fees: 0.45,
        netProfit: 19.55,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 19.55,
        executedAt: daysAgo(25, 10_000),
      },
      {
        userId: user.id,
        scanId: ids[1],
        symbol: "SOLUSDT",
        buyExchange: "bybit",
        sellExchange: "kraken",
        buyPrice: 178,
        sellPrice: 181.5,
        quantity: 5,
        grossProfit: 17.5,
        fees: 0.4,
        netProfit: 17.1,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 17.1,
        executedAt: daysAgo(20, 5_000),
      },
      {
        userId: user.id,
        scanId: ids[1],
        symbol: "ETHUSDT",
        buyExchange: "gateio",
        sellExchange: "kraken",
        buyPrice: 3195,
        sellPrice: 3235,
        quantity: 0.8,
        grossProfit: 32,
        fees: 0.55,
        netProfit: 31.45,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 31.45,
        executedAt: daysAgo(20, 12_000),
      },
      {
        userId: user.id,
        scanId: ids[2],
        symbol: "XRPUSDT",
        buyExchange: "gateio",
        sellExchange: "binance",
        buyPrice: 0.545,
        sellPrice: 0.558,
        quantity: 500,
        grossProfit: 6.5,
        fees: 0.15,
        netProfit: 6.35,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 6.35,
        executedAt: daysAgo(18, 5_000),
      },
      {
        userId: user.id,
        scanId: ids[4],
        symbol: "BNBUSDT",
        buyExchange: "kraken",
        sellExchange: "kucoin",
        buyPrice: 645,
        sellPrice: 652,
        quantity: 2,
        grossProfit: 14,
        fees: 0.38,
        netProfit: 13.62,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 13.62,
        executedAt: daysAgo(12, 5_000),
      },
      {
        userId: user.id,
        scanId: ids[4],
        symbol: "SOLUSDT",
        buyExchange: "binance",
        sellExchange: "bybit",
        buyPrice: 180,
        sellPrice: 183,
        quantity: 8,
        grossProfit: 24,
        fees: 0.45,
        netProfit: 23.55,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 23.55,
        executedAt: daysAgo(12, 10_000),
      },
      {
        userId: user.id,
        scanId: ids[6],
        symbol: "BNBUSDT",
        buyExchange: "kucoin",
        sellExchange: "gateio",
        buyPrice: 648,
        sellPrice: 655,
        quantity: 1.5,
        grossProfit: 10.5,
        fees: 0.29,
        netProfit: 10.21,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 10.21,
        executedAt: daysAgo(3, 5_000),
      },
      {
        userId: user.id,
        scanId: ids[6],
        symbol: "XRPUSDT",
        buyExchange: "kraken",
        sellExchange: "bybit",
        buyPrice: 0.55,
        sellPrice: 0.562,
        quantity: 300,
        grossProfit: 3.6,
        fees: 0.1,
        netProfit: 3.5,
        type: "arbitrage",
        side: "buy",
        status: "filled",
        realizedPnl: 3.5,
        executedAt: daysAgo(3, 10_000),
      },
      // Manual trades
      {
        userId: user.id,
        scanId: null,
        symbol: "BTCUSDT",
        buyExchange: "binance",
        sellExchange: "binance",
        buyPrice: 94500,
        sellPrice: 94500,
        quantity: 0.01,
        grossProfit: 0,
        fees: 0.28,
        netProfit: -0.28,
        type: "manual",
        side: "buy",
        status: "filled",
        realizedPnl: 0,
        executedAt: daysAgo(22),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "ETHUSDT",
        buyExchange: "kraken",
        sellExchange: "kraken",
        buyPrice: 3250,
        sellPrice: 3250,
        quantity: 0.5,
        grossProfit: 35,
        fees: 0.48,
        netProfit: 34.52,
        type: "manual",
        side: "sell",
        status: "filled",
        realizedPnl: 34.52,
        executedAt: daysAgo(21),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "SOLUSDT",
        buyExchange: "bybit",
        sellExchange: "bybit",
        buyPrice: 175,
        sellPrice: 175,
        quantity: 10,
        grossProfit: 0,
        fees: 0.44,
        netProfit: -0.44,
        type: "manual",
        side: "buy",
        status: "filled",
        realizedPnl: 0,
        executedAt: daysAgo(16),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "BNBUSDT",
        buyExchange: "kucoin",
        sellExchange: "kucoin",
        buyPrice: 660,
        sellPrice: 660,
        quantity: 2,
        grossProfit: 24,
        fees: 0.38,
        netProfit: 23.62,
        type: "manual",
        side: "sell",
        status: "filled",
        realizedPnl: 23.62,
        executedAt: daysAgo(14),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "XRPUSDT",
        buyExchange: "gateio",
        sellExchange: "gateio",
        buyPrice: 0.54,
        sellPrice: 0.54,
        quantity: 1000,
        grossProfit: 0,
        fees: 0.15,
        netProfit: -0.15,
        type: "manual",
        side: "buy",
        status: "filled",
        realizedPnl: 0,
        executedAt: daysAgo(10),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "BTCUSDT",
        buyExchange: "binance",
        sellExchange: "binance",
        buyPrice: 95800,
        sellPrice: 95800,
        quantity: 0.005,
        grossProfit: 6.5,
        fees: 0.28,
        netProfit: 6.22,
        type: "manual",
        side: "sell",
        status: "filled",
        realizedPnl: 6.22,
        executedAt: daysAgo(9),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "ETHUSDT",
        buyExchange: "kucoin",
        sellExchange: "kucoin",
        buyPrice: 3120,
        sellPrice: 3120,
        quantity: 1.0,
        grossProfit: 0,
        fees: 0.45,
        netProfit: -0.45,
        type: "manual",
        side: "buy",
        status: "filled",
        realizedPnl: 0,
        executedAt: daysAgo(6),
      },
      {
        userId: user.id,
        scanId: null,
        symbol: "SOLUSDT",
        buyExchange: "bybit",
        sellExchange: "bybit",
        buyPrice: 185,
        sellPrice: 185,
        quantity: 10,
        grossProfit: 100,
        fees: 0.44,
        netProfit: 99.56,
        type: "manual",
        side: "sell",
        status: "filled",
        realizedPnl: 99.56,
        executedAt: daysAgo(1),
      },
    ];

    await db.insert(simulatedTrade).values(trades);

    // ─── 3. Portfolio upsert ──────────────────────────────────────────────
    const totalPnl = trades.reduce((sum, t) => sum + t.netProfit, 0);
    const rounded = Math.round(totalPnl * 100) / 100;

    const existing = await db
      .select({ id: portfolio.id })
      .from(portfolio)
      .where(eq(portfolio.userId, user.id))
      .limit(1);

    if (existing.length === 0) {
      await db.insert(portfolio).values({
        userId: user.id,
        cashBalance: 100000 + rounded,
        totalPnl: rounded,
        tradeCount: trades.length,
      });
    } else {
      await db
        .update(portfolio)
        .set({
          cashBalance: 100000 + rounded,
          totalPnl: rounded,
          tradeCount: trades.length,
          updatedAt: new Date(),
        })
        .where(eq(portfolio.userId, user.id));
    }

    return NextResponse.json({
      ok: true,
      message: `Loaded ${ids.length} scans and ${trades.length} trades. Total PnL: $${rounded.toFixed(2)}`,
      scansInserted: ids.length,
      tradesInserted: trades.length,
      totalPnl: rounded,
    });
  } catch (err: any) {
    console.error("[admin/seed]", err);
    return NextResponse.json(
      { error: err.message || "Seed failed" },
      { status: 500 },
    );
  }
}
